name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: StockSharp.AdvancedBacktest.Web/package-lock.json

      - name: Install npm dependencies
        working-directory: StockSharp.AdvancedBacktest.Web
        run: npm ci

      - name: Build Next.js template
        working-directory: StockSharp.AdvancedBacktest.Web
        run: npm run build

      - name: Restore .NET dependencies
        run: dotnet restore StockSharp.AdvancedBacktest.slnx

      - name: Build .NET solution
        run: dotnet build StockSharp.AdvancedBacktest.slnx --no-restore --configuration Release

      - name: Run all tests
        run: dotnet test StockSharp.AdvancedBacktest.Tests/StockSharp.AdvancedBacktest.Tests.csproj --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            StockSharp.AdvancedBacktest.Tests/TestResults/**/*.trx
          retention-days: 7

      - name: Test summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "All unit tests, integration tests, and E2E tests completed" >> $GITHUB_STEP_SUMMARY
